### ISSUE TITLE
Try to replace MarlinDD4hep processor with GeoSvc

### ISSUE THREAD

**Issue by andresailer** [key4hep/k4MarlinWrapper#27]

**Comment by vvolkl** [comment]
I just substituted marlindd4hep in the  example in the docs with the GeoSvc, and it worked (even though the GeoSvc doesn't yet have an `EncodingStringParameter`). I'll add that option, and move the GeoSvc to a key4hep repo. Maybe `key4hep/k4FWGeo`?

**Comment by kjvbrt** [comment]
Hi,

I'm getting crashes at `m_runManager.Initialize();`, when running tests locally at Alma9/nightly stack.

```
#6  0x00007fc6c0421281 in G4RunManagerKernel::DefineWorldVolume(G4VPhysicalVolume*, bool) () from /cvmfs/sw
-nightlies.hsf.org/key4hep/releases/2023-09-03/x86_64-almalinux9-gcc11.3.1-opt/geant4/11.1.2-brmbdz/lib64/l
ibG4run.so
#7  0x00007fc6c03ff823 in G4RunManager::InitializeGeometry() () from /cvmfs/sw-nightlies.hsf.org/key4hep/re
leases/2023-09-03/x86_64-almalinux9-gcc11.3.1-opt/geant4/11.1.2-brmbdz/lib64/libG4run.so
#8  0x00007fc6c03ff9b0 in G4RunManager::Initialize() () from /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2
023-09-03/x86_64-almalinux9-gcc11.3.1-opt/geant4/11.1.2-brmbdz/lib64/libG4run.so
#9  0x00007fc6bb597d56 in SimG4Svc::initialize (this=0x36280d0) at /home/jsmiesko/Work/FCC/k4SimGeant4/SimG
4Components/src/SimG4Svc.cpp:72
```
